name: End-to-end Cypress tests
on: 
  schedule:
    - cron: '0 0 * * 1'  # Runs at 00:00 on Monday (UTC)
  # push:
  #     branches:
  #       - '**'
  workflow_dispatch:
  # - "pull_request"
jobs:
  cypress-run:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          spec: |
            cypress/e2e/src/tests/join.party.smoke.tests.ts
            cypress/e2e/src/tests/join.party.regression.tests.ts
          browser: chrome
          working-directory: ./gpoAutoTests/
